<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Arena</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="../public/css/styles.css">

</head>
<body>
	<header>
		<nav>
			<ul>
				<li class="<?= $page == 'home' ? 'selected' : '' ?>"><a href="home.php">Accueil</a></li>
				<li class="<?= $page == 'mainCreateHero' ? 'selected' : '' ?>"><a href="mainCreateHero.php">Créer son héro</a></li>
				<li class="<?= $page == 'mainHeroList' ? 'selected' : '' ?>"><a href="mainHeroList.php">Liste des héros</a></li>
				<li class="<?= $page == 'mainArena' ? 'selected' : '' ?>"><a href="mainArena.php">Arena</a></li>
			</ul>
		</nav>
	</header>